import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import UserLayout from "@/layout/UserLayout/UserLayout";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Quibe - Vibe with your world.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/quibe-favicon-32.svg" />
      </Head>
      <UserLayout>
        <div className={styles.container}>
          <div className={styles.mainContainer}>
            <div className={styles.mainContainer_left}>
              <p>Where your vibe meets the world.</p>
              <p>
                The social platform that brings your professional and personal
                life together.
              </p>
              <div
                onClick={() => {
                  router.push("/login");
                }}
                className={styles.buttonJoin}
              >
                Join Quibe Free
              </div>
            </div>
            <div className={styles.mainContainer_right}>
              <img
                src="images/hero.svg"
                alt="Hero Image"
                height="550px"
                width="auto"
              />
            </div>
          </div>
        </div>
      </UserLayout>
    </>
  );
}
